version: "3.8"
services:
  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: sentry-backend
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    image: node:16
    container_name: sentry-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

volumes:
  mongo-data:
